### ISSUE TITLE
Parser doesn't handle actions

### ISSUE THREAD

**Issue by dwmintz** [joshtemple/lkml#12]
Doesn't look like the tests cover the `action` param and the parser choked on ones in my schema

https://docs.looker.com/reference/field-params/action

I can grab the error it was throwing if that's helpful

**Comment by joshtemple** [comment]
I'm guessing you're getting a `KeyError` about `action` already existing in the tree? And you have multiple `action` definitions?

Looks like I was using an outdated documentation reference for all of the field possibilities so `lkml` didn't know that `action` and some of its child fields can appear multiple times.

This is an easy fix, I'll add it to `0.1.2` which I should be able to release in a week or so.

**Comment by dwmintz** [comment]
Sounds right.  Yes, there were multiple actions on the field
