### ISSUE TITLE
sql_where is not a plural key

### ISSUE THREAD

**Issue by dwmintz** [joshtemple/lkml#25]
To my knowledge, you cannot define more than one sql_where key as part of a JOIN.

https://docs.looker.com/reference/explore-params/sql_where

This line should be deleted:
https://github.com/joshtemple/lkml/blob/master/lkml/keys.py#L35

**Comment by joshtemple** [comment]
Multiple `sql_where` in a join _are_ allowed by the IDE validator, but it looks like only the last statement is used the SQL query. I find this to be confusing behavior. If only one will be used in the query, the validator should throw an error.

Generally, I like to stick as close to the validator as possible, but in this case, I'm okay removing `sql_where` from the list of plural keys and having `lkml` raise an error when multiple are found.

**Comment by dwmintz** [comment]
I've filed a bug internally about the validator's incorrect accepting of multiple `sql_where` definitions within the same `join`. The team has confirmed this is unintended and that they intend to fix. No estimate for when yet.
