### ISSUE TITLE
Problem with bind_filters in DerivedTables

### ISSUE THREAD

**Issue by adriantoman** [joshtemple/lkml#30]
We have this situation in one of our derived view in LookML:
view: user_activity_by_active_days{
  derived_table: {
    explore_source: active_users_count {
      column: date_grouping {}
      column: user_id {}
      column: space_name {}
      column: app_role {}
      bind_filters: {
        to_field: active_users_count.timestamp_date
        from_field: user_activity_by_active_days.filter_date
      }
      bind_filters: {
        to_field: active_users_count.event_name
        from_field: user_activity_by_active_days.event_name
      }
    }
  }

  filter: filter_date {
    type: date
  }

  filter: event_name {
    type: string
  }
}

This looks to be a valid syntax in LookML, but when I try to parse it, I get this error:
` KeyError: 'Key "bind_filters" already exists in tree and would overwrite the existing value.'`

The error makes sense, as the key is really duplicated, but tool should most likely create list of bind filters there.

**Comment by joshtemple** [comment]
Thanks for reporting this @adriantoman, looks like a typo in the plural keys is causing this. Will push out a fix and release today for this.

**Comment by joshtemple** [comment]
Fixed in `0.2.2`, please `pip install -U lkml` and try again!

**Comment by adriantoman** [comment]
Thank you very much :)
