### ISSUE TITLE
Allow parsing of new Looker 7.4 filter syntax

### ISSUE THREAD

**Issue by tpakeman** [joshtemple/lkml#32]
## Description
* [As of Looker 7.4, there is a new filter syntax](https://docs.looker.com/relnotes#new_lookml_syntax)
* This allows filters in the format `filters: [field: value, field: value]`

**Comment by joshtemple** [comment]
Thanks for bringing this to my attention Tom! This requires a fairly significant change to the parser to support this syntax since the [current parser grammar](https://github.com/joshtemple/lkml/blob/master/lkml/parser.py#L34) assumes anything in square brackets is a comma separated list. Hopefully I'll have some time to tackle this in the near future.

**Comment by tpakeman** [comment]
No problem! I forked your repo to give it a go myself, then realised quite quickly how hard it would be 😅- good luck!

**Comment by joshtemple** [comment]
@tpakeman, actually curious to know why this syntax was chosen instead of `{key: value}` with braces. Everything else in Looker is key value pairs with braces, except for the set-type syntax with brackets. I don't see a reason why an array of key value pairs makes sense within LookML. Do you have any insight or know anyone at Looker who does?

**Comment by bplmp** [comment]
I'm having the same problem with this, as the new syntax broke our tests that use the lkml package...

My solution for now was to ask people to use the old syntax. I agree with @joshtemple that this new syntax looks VERY weird. I've commented on it here https://discourse.looker.com/t/looker-7-4-release-notes/16767

**Comment by fabio-looker** [comment]
FYI, I've just added support to my node parser (v 6.3)

https://github.com/fabio-looker/node-lookml-parser/issues/8

I also would have liked a more traditional LookML syntax here, & unfortunately I don't have direct visibility into why this syntax was chosen :shrug:

**Comment by Spacerat** [comment]
Hi! I ran into this problem myself and threw together a fix. I went to create a Github issue, then noticed this one already exists.

Here's the complete workaround I'm currently using:

```py
import io

import lkml.tokens as tokens
from lkml.lexer import Lexer
from lkml.parser import DELIMITER, Parser as BaseParser
from typing import Optional, Union, IO

def _pair_to_field_value(pair) -> dict:
    key, value = next(iter(pair.items()))
    return {
        "field": key,
        "value": value
    }

class Parser(BaseParser):
    """ Patches the LKML parser to support key/value pairs inside lists, e.g.

        filters: [key: "value", key2: "value2"]
    """

    @BaseParser.backtrack_if_none
    def parse_csv(self) -> Optional[list]:
        if self.log_debug:
            grammar = '[csv] = (literal / quoted_literal) ("," (literal / quoted_literal))* ","?'
            self.logger.debug("%sTry to parse %s", self.depth * DELIMITER, grammar)
        values = []

        pair = self.parse_pair()  # Fix is here: try to parse the value as a pair
        if pair: 
            values.append(_pair_to_field_value(pair))
        elif self.check(tokens.LiteralToken, tokens.QuotedLiteralToken):
            values.append(self.consume_token_value())
        else:
            return None
        

        while not self.check(tokens.ListEndToken):
            if self.check(tokens.CommaToken):
                self.advance()
            else:
                return None

            pair = self.parse_pair()  # Same fix reapplied here
            if pair:
                values.append(_pair_to_field_value(pair))
            elif self.check(tokens.LiteralToken, tokens.QuotedLiteralToken):
                values.append(self.consume_token_value())
            elif self.check(tokens.ListEndToken):
                break
            else:
                return None

        if self.log_debug:
            self.logger.debug(
                "%sSuccessfully parsed comma-separated values.", self.depth * DELIMITER
            )
        return values
```

Happy to turn this into a PR if you like the look of it.
