### ISSUE TITLE
Plans to support Looker "include" filesystem resolution

### ISSUE THREAD

**Issue by grantatspothero** [joshtemple/lkml#41]
One thing we want to do is ingest an entire directory of LookML and resolve references between files. 

For example, a Looker view is bound to a specific model [when the the view is included in the model definition file](https://docs.looker.com/reference/model-params/include#including_views_and_dashboards_in_a_model). Until you bind a view to a specific model, you actually do not know which connection the view is referencing. 

Another example, to understand a view definition completely, you need to resolve [view extends](https://docs.looker.com/reference/view-params/extends-for-view). Since Looker views can extend other views in other files, again you have to ingest the entire directory of LookML and resolve references. 

This might be completely out of scope, but it would be nice to have an interface to ingest a directory on the filesystem and build a graph of Looker objects with dependencies resolved between them.

**Comment by joshtemple** [comment]
This is a cool idea! However, this isn't something I would be willing to add to `lkml`, as it goes beyond parsing LookML. It would be better served as a separate tool that uses `lkml` to parse the LookML, then builds the graph of references from the parsed result.

I'd love to take a look if you end up building this though!
