### ISSUE TITLE
Parser fails when parsing explore "filters"

### ISSUE THREAD

**Issue by grantatspothero** [joshtemple/lkml#42]
The test cases included in this repo show the explore filters as follows:
https://github.com/joshtemple/lkml/blob/46b7917953baf804a4f18defd81f052dec71293c/tests/resources/model_with_all_fields.model.lkml#L104-L109

However the official looker docs show explore filters with a different format (brackets instead of curly braces):
https://docs.looker.com/reference/explore-params/always_filter

This causes parsing of looker model files to fail if they contain the proper looker filter syntax. I tried the curly braces format in Looker's UI and it failed their LookML validation, so I think the proper syntax is indeed the brackets.

**Comment by joshtemple** [comment]
Closing this as a duplicate of #32. I'm working on a fix for this which will be released in version 1.0.
