### ISSUE TITLE
Quotes not escaped using lkml.dump(…)

### ISSUE THREAD

**Issue by oparaskos** [joshtemple/lkml#46]
When deserialising a quote (") in a string using `lkml.dump(…)` quotes are added around the whole string, but the quotes inside the string aren't escaped leading to invalid lkml.

Present workaround is to do str.replace("\"", "\\\"") before setting the value of the field.

**Comment by joshtemple** [comment]
Thanks Oliver. What version of lkml are you using here?

**Comment by oparaskos** [comment]
`lkml                1.0.0`

This is the version i got yesterday when i ran `pip3 install lkml` for the first time.
