### ISSUE TITLE
Whitespace not stripped from looker table name

### ISSUE THREAD

**Issue by bcipolli** [joshtemple/lkml#47]
This is a change (and I assume a regression), sometime between 0.2.2 and 1.0.0 (installed today).

```
  sql_table_name: entrepot.annotated_donations ;;
```

view['sql_table_name'] returns: ` entrepot.an...ed_donations ` with leading and trailing whitespace, rather than `entrepot.annotated_donations`

This is not how Looker thinks about it (Looker strips whitespace). And, this is the [recommended style to use](https://docs.looker.com/reference/view-params/sql_table_name-for-view) by Looker.

**Comment by joshtemple** [comment]
Hey Ben! I'm pretty sure this issue is a duplicate of #45. It is a regression and I think I should have a fix out today or tomorrow. Unless you think this is something different, I'll close this in favor of #45.

**Comment by bcipolli** [comment]
Wasn't sure, sounds good!
