### ISSUE TITLE
Raises exception on hanging comma in list

### ISSUE THREAD

**Issue by weightwatchers-carlanderson** [joshtemple/lkml#5]
The parser complains
```
   f"Unable to find a matching expression for '{token.id}' "
SyntaxError: Unable to find a matching expression for ']' on line
```
if it is receives a list with a final comma such as 
```
timeframes: [
      date,
      week,
      month,
    ]
```
However, the Looker validator passes this as valid

**Comment by weightwatchers-carlanderson** [comment]
full example file to test against:
```
view: dim_geography {
 sql_table_name: `BQDW.DimGeography` ;;

  dimension_group: current_week_start {
    type: time
    timeframes: [
      date,
      week,
      month,
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.CurrentWeekStart ;;
  }

}
```

**Comment by weightwatchers-carlanderson** [comment]
@joshtemple I have tiny pull request that will fix this (retains normal strict mode but a simple flag in Parser allows it allow final commas in list). However, I don't have permission to push to this repo

**Comment by joshtemple** [comment]
@weightwatchers-carlanderson, thanks for the PR! Could you please fork this repo, push your changes to the fork, and then create the PR from there [as shown here](https://gist.github.com/Chaser324/ce0505fbed06b947d962)?

The same applies for #6.
