### ISSUE TITLE
lkml.dump deletes "name" key from dict

### ISSUE THREAD

**Issue by victoryifei** [joshtemple/lkml#61]
[dump](https://github.com/joshtemple/lkml/blob/3d629172bbc97a93f1d5f5af0cf4f219752a1ca8/lkml/__init__.py#L56) function mutates input dict by removing all "name" fields in the dict.
Looks like it is caused by a `.pop` call on [this line](https://github.com/joshtemple/lkml/blob/3d629172bbc97a93f1d5f5af0cf4f219752a1ca8/lkml/simple.py#L312).

**Comment by joshtemple** [comment]
Please provide an example and explain why this behavior doesn't work for you use case. Thanks!

**Comment by ryan-duve** [comment]
@joshtemple This is also breaking for us for the same reason as @victoryifei described.  Here is a minimum working example using `lkml=1.2.0`:

```
In [1]: import lkml
   ...:
   ...: MY_JOINS_CONSTANT = [{"name": "foreign_key_table", "sql_on": "sql_goes_here"}]
   ...:
   ...:
   ...: print(f"{MY_JOINS_CONSTANT=}")
   ...:
   ...: explores = [{"joins": MY_JOINS_CONSTANT}]
   ...: model_lkml = {"datagroups": [{"explores": explores}]}
   ...: lkml.dump(model_lkml)
   ...:
   ...: print(f"{MY_JOINS_CONSTANT=}")
   ...:
MY_JOINS_CONSTANT=[{'name': 'foreign_key_table', 'sql_on': 'sql_goes_here'}]
MY_JOINS_CONSTANT=[{'sql_on': 'sql_goes_here'}]
```

We are using that constant in more than one place and were not expecting `lkml.dump()` to modify it.  The above comment describes both our usecase and the problem.

Let us know if there's any more detail that can be provided to help make the difficulty clear/what we can do to offer a fix for the issues, and thanks so much for providing and maintaining this absolutely excellent library!

**Comment by ryan-duve** [comment]
@joshtemple This is also breaking for us for the same reason as @victoryifei described.  Here is a minimum working example using `lkml=1.2.0`:

```
In [1]: import lkml
   ...:
   ...: MY_JOINS_CONSTANT = [{"name": "foreign_key_table", "sql_on": "sql_goes_here"}]
   ...:
   ...:
   ...: print(f"{MY_JOINS_CONSTANT=}")
   ...:
   ...: explores = [{"joins": MY_JOINS_CONSTANT}]
   ...: model_lkml = {"datagroups": [{"explores": explores}]}
   ...: lkml.dump(model_lkml)
   ...:
   ...: print(f"{MY_JOINS_CONSTANT=}")
   ...:
MY_JOINS_CONSTANT=[{'name': 'foreign_key_table', 'sql_on': 'sql_goes_here'}]
MY_JOINS_CONSTANT=[{'sql_on': 'sql_goes_here'}]
```

We are using that constant in more than one place and were not expecting `lkml.dump()` to modify it.  The above comment describes both our usecase and the problem.

Let us know if there's any more detail that can be provided to help make the difficulty clear/what we can do to offer a fix for the issues, and thanks so much for providing and maintaining this absolutely excellent library!

**Comment by joshtemple** [comment]
Thanks @ryan-duve for the example! I understand this issue better now and I'll get a fix pushed out in the next few days where we don't mutate that input directly.
