### ISSUE TITLE
new post-1.1.0 release?

### ISSUE THREAD

**Issue by jameslamb** [joshtemple/lkml#65]
Thanks for this awesome project!

Would you consider pushing a new minor release to PyPI?

v1.1.0, the [most recent release on PyPI](https://pypi.org/project/lkml/#history), went up on January 26, 2021. There have been a handful of bugfixes since then, and I'd like to be able to use a version of `lkml` with those fixes form a package manager.

I'm currently relying on `lkml` through `acryl-datahub` to do metadata ingestion for LookML files, and am pinning to a build from GitHub here to get the fixes from #64.

Thanks for your time and consideration.

**Comment by joshtemple** [comment]
Done! Sorry this took me so long. I've released v1.1.1 with the latest changes on the main branch.

**Comment by jameslamb** [comment]
awesome, thanks!
