### ISSUE TITLE
lkml only parses a single constant, even when multiple constants are defined

### ISSUE THREAD

**Issue by EyalDlph** [joshtemple/lkml#92]
in this example model.lkml file:
```
        connection: "my_connection"

        constant: my_constant {
          value: "my_value"
        }

       constant: other_constant {
          value: "other_value"
       }

        view: view_name {

          sql_table_name: my_schema.table_name ;;

          dimension: dimension_name {
            type: string
            sql: ${TABLE}."field_name" ;;
            description: "this is a dimension"
          }
        }


        explore: view_name {
        }
```

parsing with lkml yields:
```
{'connection': 'my_connection',
 'constant': {'value': 'other_value', 'name': 'other_constant'},
 'views': [{'sql_table_name': 'my_schema.table_name',
   'dimensions': [{'type': 'string',
     'sql': '${TABLE}."field_name"',
     'description': 'this is a dimension',
     'name': 'dimension_name'}],
   'name': 'view_name'}],
 'explores': [{'name': 'view_name'}]}

```
notice that only a single constant is parsed.

I'd expect that `constant` will be a list (maybe rename to `constants`)

**Comment by EyalDlph** [comment]
wrong file. constant are defined in manifest.lkml.

**Comment by EyalDlph** [comment]
the example I provided is wrong, since `constant` is not a valid block in model.lkml, but it is valid in `manifest.lkml`. So same argument applies.

**Comment by luca-pesenti-sdg** [comment]
I have the same issue. Did you find any workaround? Thank! :)

**Comment by joshtemple** [comment]
Thanks! The manifest file isn't very well-tested for `lkml`. Looks like we need to add `constant` to `PLURAL_KEYS` here:

https://github.com/joshtemple/lkml/blob/f2a618353844c10a7f146b40ef55a7d74909928e/lkml/keys.py#L12-L46
